### ISSUE TITLE
how

### ISSUE THREAD

**Issue by mohghezal** [Arachni/arachni#1073]
how scan list urls.txt

**Comment by anasbousselham** [comment]
Interesting

**Comment by Zapotek** [comment]
Due to the fact that each scan has/requires its own configuration this hasn't been implemented.

You'll need to script it yourself and pass appropriate parameters for each target you wish to scan.

My answer of course assumes that urls.txt contains targets, otherwise, to extend a scans scope have a look at: https://github.com/Arachni/arachni/wiki/Command-line-user-interface#scope-extend-paths
