### ISSUE TITLE
Publicly Writable Directory Check

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#561]
I just finished a scan of a tomcat server that had every HTTP option known to man enabled.  Arachni correctly found and exploited the PUT method with the publicly writable directory check, which is great, however it did not identify the DELETE option.

Also, I had to manually go through and delete the ~50 files Arachni created with curl.  This was mildy annoying, so I thought I would request a few things:

1.  Is there a smarter way for Arachni to verify the PUT method issue at a server level instead of creating a file at each directory?  Manually removing the files in this case wasn't terrible, but I can see being more of a pain for a bigger app (especially if the DELETE method isn't also enabled and I have to give the customer a big list of files they need to delete themselves).

2.  If Arachni detects both PUT and DELETE enabled on a server, would it make more sense to PUT a file, check that it's there, and then delete it?

**Comment by Zapotek** [comment]
The `allowed_methods` check will tell you all available methods, given that the server advertises them properly.

1. It could ask the server to tell it which methods are supports via the `OPTIONS` method, but unless a `PUT` is actually successful then I can't claim that a directory is actually writeable.
2. I'll add a `DELETE` request for the uploaded file anyways, if it works that's cool, otherwise no biggie.

Sound good?

**Comment by cclements** [comment]
Yep, that works for me.  Thanks!

**Comment by Zapotek** [comment]
All done!

Mind taking [v1.1](https://github.com/Arachni/arachni/tree/v1.1#linux-and-osx) for a spin? I'd like it to get as much testing as possible while I work out a build issue and then I'll release it.

Also, if you've got any sites with JSON/XML requests all the better, this is a new feature and hasn't gotten much real-world exercise.

Cheers

PS. Don't recall if I've asked you to test it before, I ask everyone. :)
