### ISSUE TITLE
E-mail address identification using regular expression

### ISSUE THREAD

**Issue by anandrajessar** [Arachni/arachni#570]
Arachni' s regular expression for finding e-mail addresses in a web page is not accurate. White listing known domain names will be better. See the attached screenshot for clarification. An image file 'Splash@2x.png ' is wrongly identified as an e-mail address.
![arachni-bug](https://cloud.githubusercontent.com/assets/5228664/6881009/e9d615d4-d571-11e4-82d7-04ef3d8d0dc7.PNG)

**Comment by Zapotek** [comment]
Hello,

The regular expression is accurate in the sense that it matches valid e-mail addresses.
Whether or not those addresses are actually active is impossible to verify and using a white-list is not really possible since you can't have a white-list that includes every SMTP server on the planet.

So, all things considered I'm OK with it results.

Cheers,
Tasos L.
