### ISSUE TITLE
Arachni only sends cookie store on first two reqeusts to webserver

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#586]
Hello,

Arachni is only sending the cookie store on the first two requests to the web server.  The rest of the requests use the cookies sent from the response of the request, which doesn't help for an authenticated scan.

**Comment by Zapotek** [comment]
I'm sorry I kind of lost you, do you have an example of this issue visible via the `--output-debug=3` flag?

**Comment by sbehrens** [comment]
First two requests to url:

```
GET /youraccount HTTP/1.1
Host: www.redacted.com
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:32.0) Gecko/20100101 Firefox/32.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cookie: obfuscated1=foo; obfuscated2=bar; obfuscated3=sue; obfuscated4=nancy
```

Response contains something like:

```
...snip
Set-Cookie: clid=f8b43661-1589-4550-990a-blah; Domain=.redacted.com; Expires=Fri, 13-May-2016 15:40:41 GMT; Path=/
Set-Cookie: sss-rgn=uw2|1431618041888; Domain=.redacted.com; Path=/
Set-Cookie: tlr=US|1431618041890; Domain=.redacted.com; Expires=Sun, 08-May-2016 15:40:41 GMT
snip...


Then every single request for the rest of the scan looks like this:

```
GET /WiSearch?raw_query=_arachni_trainer_a8b630aab385b6f19f7c93c67021de40&ac_category_type=none&ac_rel_posn=-1&ac_abs_posn=-1&v1=1&search_submit=1 HTTP/1.1
Host: www.redacted.com
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:32.0) Gecko/20100101 Firefox/32.0 
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cookie: sss-rgn=uw2|1431618041888; tlr=US|1431618041890;clid=f8b43661-1589-4550-990a-blah;
```


I can reproduce this behavior every-time.  It is like it takes the set-cookie object and uses that as the cookies for the rest of the requests instead of sending hate original cookie string I specify.

**Comment by Zapotek** [comment]
We'll have to take this discussion to e-mail in order to see the de-obfuscated data along with the way you specified the cookies initially.

I don't think there's a bug in Arachni, these cookie issues usually have to do with the little things like expiration dates, paths, domains etc.
Sensitive stuff that play a bit part.

**Comment by sbehrens** [comment]
Okay, thanks I'll forward this via your email.

**Comment by Zapotek** [comment]
This issue was resolved over e-mail and it turns out to have been caused by a configuration issue.
The target URL was in the form of `http:///www.domain.com/some-path` and the cookies were specified by `--http-cookie-string=mycookie=myvalue`.

In that scenario, the system uses the target URL in order to fill-in missing cookie attributes such as `path` (`/some-path`) and `domain` (`www.domain.com`); as per the RFC, this leads to cookies not being set to any non-applicable path, thus resulting in the observed behavior.

Use of a [cookie-jar](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#http-cookie-jar) or was advised instead.

The documentation of the [--http-cookie-string](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#http-cookie-string) option was updated to warn about this behavior.
