### ISSUE TITLE
Timeout appears to do nothing..

### ISSUE THREAD

**Issue by bstream** [Arachni/arachni#590]
Hey!

I want to report an error and ask a question about the timeout option.
**Error**
I ran a scan with `--timeout=00:01:00` so that the scan would be aborted after 1 minute.
When the timeout was reached I was the message `[-] Timeout has been reached, shutting down.` but then the scan continued until interrupted manually or until it was finished scanning. 
* Command used: `./bin/arachni http://target/application --profile-load-filepath=custom.profile.afp --timeout=00:01:00`
* Output snippet: https://gist.github.com/bstream/31e49f0525c5b8253864 

(This may be related to #587)

**Question** 
At the moment the scan will generate an error log if the timeout is reached with the contents `Timeout has been reached, shutting down.`. Since I supply the timeout I don't regard it as an error if it is triggered. Instead, maybe it could be indicated in the scan report, like `"timeout_reached" : True/False`? Or, I guess it could be reported as a potential issue in the report, since not running a *full scan* could mean that vulnerabilities are missed.

**Comment by Zapotek** [comment]
Hello there,

Which version are you using?
Also, are you using the official packages?

**Comment by bstream** [comment]
Sorry, totally missed that!

I am using the latest Linux x86 64bit version available on http://www.arachni-scanner.com/download/ (v1.1-0.5.7).

**Comment by Zapotek** [comment]
I could go into it but this sums it up nicely: http://plasmasturm.org/log/6debug/

Pushing the fix shortly.

**Comment by Zapotek** [comment]
Thanks for the feedback Andreas.

**Comment by bstream** [comment]
No problem! Thanks for the quick fix ;)

Did you have time to check out the question(s) in the main post? (I guess they are easily overlooked.. ;) )

**Comment by Zapotek** [comment]
Sorry, bit sleepy.

The options and the scan duration are in the report, so it's quite easy to see if that was indeed the case.
I do like that idea if it covers all cases though (`aborted`, `suspended`, `timed_out`).

Can you please open a feature request? I'll work on it for v1.3, v1.2 is close to being released and I don't want to mess with the report format last minute.

As for the message being logged as an error, I do see it as an error.
The timeout option is there to kill possibly runaway scans, as it stops the scan before proper coverage has been reached, which is counter to the point of the scan.
If a scan dies due to RAM exhaustion I'd like for that to be logged as an error, in this case the exhausted resource was time.

If the user wishes to instead restrict the scan, they should do so via the scope options.

Cheers

**Comment by bstream** [comment]
Ok, fair enough :)

Opened a feature request: #591
