### ISSUE TITLE
Flase positive for "E-mail address disclosure in Body"

### ISSUE THREAD

**Issue by shakir1311** [Arachni/arachni#618]
Arachni considered image@2x.png as an email address.

**Comment by Zapotek** [comment]
That's interesting.

Technically, it is a valid e-mail address, format wise, but short of actually contacting the SMTP server to check if it's active there's not much that can be done.

The only viable alternative I can think of is to only log addresses for the targeted domain, which I guess is fair enough since that's the scan scope in the first place.

Thoughts?

**Comment by shakir1311** [comment]
"only log addresses for the targeted domain"
Not sure. I am not expert in that. What if there are actual emails but not from same domain. e.g emails of customers on a banking site!!

"Remedy"
Maybe: a simple ping to "2x.png" can reveal to Arachni that the domain is not actual domain. (but we should be cautious as some attacker can use this to host a site with a corrupt email and when Arachni pings the domain send malicious data back and complicate everything).

**Comment by Zapotek** [comment]
Yeah can't really go around making connections to 3rd party systems.
And the e-mail disclosure check is intended as a recon helper rather than to spot information leakage; finding e-mail addresses to be used for social engineering and the like.

I think I better treat them as any other address and enforce the same scope restrictions, i.e. same domain only.

**Comment by shakir1311** [comment]
I am still not convinced by same domain thing. An organization may have many domain names.

Why not we just add 2x.png as a strong case for false positive or maybe just excluding 2x.png

**Comment by Zapotek** [comment]
It's impossible to build a list like that, `2x.png` isn't a strong case for a false-positive.
Maybe blacklist only known file extensions (i.e., just `.png` part) but that still doesn't mean anything, you can get whatever TLD you want now.
And, again, that doesn't solve the problem since this is a general issue of strings matching the right format for e-mail addresses, not just asset files.

About the different domain names, that's true, but the same can be said about any other resource, however the scanner has very clear scope that it needs to enforce.
`example.com` may have a form posting to `another-example.com`, regardless of who the owner is, that form is going to be ignored because it's out of scope.

The choices basically are:

1. Connect to to 3rd party servers -- which is unacceptable.
2. Continue to blindly match strings that match a valid e-mail address format -- blacklists aren't a solution, will keep logging the occasional non-existent address.
3. Only log addresses within scope -- FPs pretty much fixed, consistent with the handling of any other resource, fulfils the intended functionality of the check.

The last solution may not cover everyone's needs, but it is the most fitting.

**Comment by shakir1311** [comment]
I would choose to trust your judgement :) I am not the expert and I am (and everyone using this tool) is extremely thankful for your work. By the way do we have an IOS app for running Arachni. If not then I can contribute towards that. The reason is that in my organization we can easily test something from our iPhone but installing an app on corporate machines requires lots of approvals. Plus having a mobile app makes the tool much convenient to use

**Comment by Zapotek** [comment]
I'm just spitballing, the solution usually lies somewhere in the middle, I'll keep thinking about it, see if I can come up with a better compromise.

About the IOS thing, can't say I'd be interested in supporting that long term.
I do usually get curious and I've spotted ways to run Ruby apps on mobile systems but I don't think it would be worth the effort or if it would be practical.
You're much better off running the WebUI somewhere and controlling it from a whatever device you want via a browser.

I suppose having Arachni on your mobile device would be helpful for on-site visits, but I doubt that a pen tester doing an on-site visit to a client wouldn't bring a proper laptop, so we're back to running the WebUI on that and controlling it from anywhere.

**Comment by Zapotek** [comment]
After a brief chat with @treadie, who provided ample examples of serious real world issues identified as a result of the current behavior, it became clear that I should not be a disk and ruin it.

So, since connecting to the mail server is unacceptable, the compromise seems to be just doing a DNS resolution on the domain name, that should be enough to remove false-positives.

**Comment by Zapotek** [comment]
Btw, setting this for v1.4, the one after the upcoming one.
I don't completely trust the stability of that approach to release it immediately.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up and include DNS resolution for the domains of e-mail addresses.

Beware though that the nightlies include **a lot** of [fresh code](http://www.arachni-scanner.com/blog/massive-performance-optimizations-now-in-the-nightlies/) so if you come across any bugs please let me know.
