### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by benwalther** [Arachni/arachni#631]
Receiving the following error on `bundle`

```
Using arachni (1.3.2) from source at /github.com/arachni 
ArgumentError: invalid byte sequence in US-ASCII
An error occurred while installing arachni (1.3.2), and Bundler cannot continue.
Make sure that `gem install arachni -v '1.3.2'` succeeds before bundling.
```

Environment:
```
# uname -a
Linux e3d8e796b6a0 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

# ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

# echo $LANG
en_US.UTF-8
# echo $LANGUAGE
en_US.UTF-8
# echo $LC_ALL
en_US.UTF-8
```

Any ideas?

**Comment by Zapotek** [comment]
Hello,

The Arachni Framework isn't compatible with Ruby versions <= 2.0.0.
One of the reasons for that is the poor handling of character encodings, which in this case didn't even give the system the chance to let you know of the first fact in a nice manner but instead blew up.

Is there a specific reason that you're working with the source instead of using the [official self-contained packages](http://www.arachni-scanner.com/download/) though?

**Comment by benwalther** [comment]
Ah! Missed the ruby language requirement. Thanks a bunch.

And just testing it out in a docker build. Wanted the image to always build the latest version, rather than constantly downloading from your site.

**Comment by Zapotek** [comment]
Better download the packages, handling the system's dependencies can be tricky.
Alternatively, check out the [build scripts](https://github.com/Arachni/build-scripts#arachni-build-scripts).

**Comment by benwalther** [comment]
`wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash -s build_and_package` is my new favorite. Didn't even see that repo. Thanks again.

**Comment by Zapotek** [comment]
I don't think you need to package since you'll probably immediately extract the archive, this should be enough:

    wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash

Take a look at the other options too, it grabs the experimental branches by default.
