### ISSUE TITLE
Disclosed US Social Security Number (SSN) in Body

### ISSUE THREAD

**Issue by ecoitsolutions** [Arachni/arachni#632]
Hi there,
I think this check should be double checked because can lead to many false positives, like in my case. 
There will always be blocks of numbers inside body for various reasons.

**Comment by Zapotek** [comment]
Hello,

Apart from the SSN format there's not much else that can be done to verify whether or not a block of numbers really is an SSN.
The best I can do is mark such issues as untrusted by default, thus deprioritizing them in the reports and not have them appear alongside trusted issues.

Just so that I can have a better picture of the issue, would you mind privately sending me the AFR report?

Cheers

**Comment by ecoitsolutions** [comment]
Thank you,
I will attach it once it finishes (large magento store to check).
Cheers

**Comment by Zapotek** [comment]
Better send it to: tasos[dot]laskos[at]arachni-sanner.com

**Comment by Zapotek** [comment]
I've updated the `ssn` check to flag its issues as untrusted by default.
There isn't an algorithm to check validity like there is for CCs and other similar numbers, so blame the US government for the inconvenience. :)

**Comment by ecoitsolutions** [comment]
Thanks! ;)

Sent from my iPhone

On 08 Nov 2015, at 02:25, Tasos Laskos <notifications@github.com> wrote:

I've updated the ssn check to flag its issues as untrusted by default.
There isn't an algorithm to check validity like there is for CCs and other
similar numbers, so blame the US government for the inconvenience. :)

—
Reply to this email directly or view it on GitHub
<https://github.com/Arachni/arachni/issues/632#issuecomment-154769163>.
