### ISSUE TITLE
Name resolution over socks proxy

### ISSUE THREAD

**Issue by tbearden** [Arachni/arachni#635]
No way to perform name resolution over a socks proxy.  It looks like the socksify lib already supports this functionality, so just need to show it in UI and use that functionality.

**Comment by tbearden** [comment]
Didn't appear to be. I was trying to use tor as my proxy to scan a hidden
site, but I was getting a 'couldn't resolve host' type of error. Proxy
itself was working fine for non-hidden sites.

**Comment by Zapotek** [comment]
Interesting, I'll look into to it and keep you posted.

Thanks for the feedback.

**Comment by Zapotek** [comment]
Btw, where are you getting this error from?

**Comment by tbearden** [comment]
Web ui when running a scan.  I will get you more specifics later

**Comment by Zapotek** [comment]
OK, I'm waiting to hear from you.
Interface screenshot and/or errors logs would help.

**Comment by Zapotek** [comment]
Turns out `libcurl` needed a different option in order to perform the resolution via the proxy.
I've added it to the Framework and configured the WebUI's profile form to show available options as a drop-down.

The option you want is `socks5h`.

I'll let you know once fresh nightlies are up so that you can take them for a spin.

Cheers

**Comment by tbearden** [comment]
Awesome, thanks for looking into this!

**Comment by Zapotek** [comment]
OSX and Linux nightlies are up, Windows still pending.

**Comment by Zapotek** [comment]
Windows nightly is up too.

Cheers
