### ISSUE TITLE
Ability to limit DOM state audits per page or per scan

### ISSUE THREAD

**Issue by gigabuck** [Arachni/arachni#663]
This is a feature request to add the capability to restrict the number of DOM state/snapshot audits per sitemap page.

When trying to limit scan times, one approach taken is to set [--scope-page-limit](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#scope-page-limit) to limit the number of URLs audited. However, with the addition of the browser environment, this is no longer a true count since it doesn't factor in auditing DOM state/snapshot per page and is only a count of unique URLs in the sitemap. It would be helpful to have a `--scope-dom-state-per-page-limit` or something similar option to limit the number of audited DOM states/snapshots per actual page.

See the following [support discussion](http://support.arachni-scanner.com/discussions/problems/3937-scope-page-limit-does-not-restrict-max-pages) for additional details.

**Comment by Zapotek** [comment]
This is how I see this being implemented:

 `--scope-dom-event-limit=3` would only trigger the first 3 events on any snapshot, resulting in a maximum of 3 pages one level deeper in the DOM.
However, that would be applicable per snapshot, not per unique URL/resource, otherwise you'll miss out on depth and never get a chance to exercise the webapp properly.

This way you get to configure both the depth (with the existing `--scope-dom-depth-limit` option) and breadth.

Not 100% sure on the above but I think it makes some sense.

**Comment by Zapotek** [comment]
Nightlies are up.
