### ISSUE TITLE
Arachni_reproduce can't reproduce 'interesting response'

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#720]
I've been trying the `arachni_reproduce` feature, but I can't get it to reproduce the `interesting response` checks.
I can reproduce the `interesting respose` (http status 403, in my case) manually in a browser, so it seems odd that `arachni_reproduce` can't.

The `arachni_reproduce` output shows that it's reproducing on the referring URL rather that the URL where the issue was discovered in the original scan.
 
This is my scan command:
`arachni [doamin] --scope-exclude-binaries --scope-auto-redundant='2' --plugin='metrics' --plugin='autothrottle' --plugin='timing_attacks' --plugin='uniformity' --http-request-concurrency='10' --scope-page-limit=1`

**Comment by Zapotek** [comment]
This is because the `interesting_responses` check doesn't actually do anything, it's completely passive.
The responses it logges are for requests made by other checks.

I could just replay the request but it won't be reliably, although at the very least I should maybe show a message explaining the situation.

**Comment by Zapotek** [comment]
I just noticed, there already is a message explaining the situation:

>  [~] These issues could not be replayed, they may have been fixed or **require a workflow that can only be triggered by a full scan**.
