### ISSUE TITLE
CLI only package

### ISSUE THREAD

**Issue by Joeyn414** [Arachni/arachni#831]
*Not an issue, feature question*
Have you thought about making a CLI only package. I use your product in a CICD such as Jenkins inside docker containers (which I can forward to you if you want) and I dont have any use for any of the UI portions. I do like the reporter function so I wouldn't want any of that to go, but a more slimmed down working version of CLI only would be great and make my docker container much smaller.

If this is something you are looking for a collaborator on I would work on it with you. I would just need to figure out which components can be safely removed and still allow the CLI portions to function.

**Comment by Zapotek** [comment]
Sounds like you just want the Framework without the WebUI, see: https://github.com/Arachni/arachni/wiki/Installation#nix-source-based
For the time being, prefer [checking out the git repo](https://github.com/Arachni/arachni/wiki/Installation#nix-source) instead of using the [Gem](https://github.com/Arachni/arachni/wiki/Installation#nix-gem), there's an issue with it currently.

If you plan to use the `experimental` branch instead of the `master` one, then you'll need PhantomJS 2.1.1 instead of 1.9.2.

As for Framework-only packages, I'm not interested in providing them, you'll need to install all dependencies yourself by following the Wiki instructions I mentioned.

Cheers
