### ISSUE TITLE
Authentication problem with OAM implemented web applications

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#860]
Dear Tasos,

We have some web applications to test which are using OAM (Oracle Access Management). In this case, we have say 3 URLs www.test1.com, www.test2.com and www.test3.com. Now all the 3 URLs navigate to same login page (www.login.aspx) when clicked on Login button. Consider the credentials are also same for all the 3 web apps. Not login.aspx decide the home page (posy authentication page) by reading the referer header and its value while navigating to login.aspx.

I would like to understand, how we can achieve authenticated scan in this case?

Regards,
Pankaj

**Comment by Zapotek** [comment]
Your best bet is to write a login script that uses the system browser: http://support.arachni-scanner.com/kb/general-use/logging-in-and-maintaining-a-valid-session#with-browser-slow-

**Comment by theinfosecguyPankaj** [comment]
Dear Tasos,

Please respond to.my query.

**Comment by Zapotek** [comment]
Your issue seems to be with the `exec` plugin, the `login_script` ran without error.

Regarding the login check, surely there must be some request (even a POST one) that you can make to make sure you have a valid session, otherwise a logged-in user's interface would be identical to a guest.
See: http://support.arachni-scanner.com/kb/general-use/logging-in-and-maintaining-a-valid-session#advanced-session-check-configuration
