### ISSUE TITLE
Blind SQL Injection (timing attack)   misinformation

### ISSUE THREAD

**Issue by chushuai** [Arachni/arachni#889]
when waf  filter request, It  make mistakes;

**Comment by Zapotek** [comment]
I'm not sure what you mean, can you show some more details?
Maybe tell me how to reproduce it by performing an identical scan?

Also, Arachni is not meant to be ran against applications that are behind security measures, because then it wouldn't be scanning the application but the things that are in between. Still, if I could make it more resilient I'd like to give it a shot.

**Comment by Zapotek** [comment]
Closing due to lack of feedback.
